import type { Item, McqItem, TbsItem } from '@opencpa/schema';
// Generated by `pnpm content:build` from reviewed items in /content.
import raw from './generated/content.json';

export const items = raw as unknown as Item[];
export const byId = new Map(items.map((i) => [i.id, i]));
export const mcqs = items.filter((i): i is McqItem => i.type === 'mcq');
export const simulations = items.filter((i): i is TbsItem => i.type === 'tbs');
